"""empty message

Revision ID: 088292198ad4
Revises: 1afdfe4c6f7f
Create Date: 2024-12-06 22:13:25.926475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088292198ad4'
down_revision = '1afdfe4c6f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
