"""empty message

Revision ID: 1afdfe4c6f7f
Revises: ac973ca37aef
Create Date: 2024-12-06 22:09:17.194233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afdfe4c6f7f'
down_revision = 'ac973ca37aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('fnumber', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'fnumber')
    # ### end Alembic commands ###
