"""empty message

Revision ID: ac973ca37aef
Revises: 78b9ca58a268
Create Date: 2024-12-06 22:08:31.100259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac973ca37aef'
down_revision = '78b9ca58a268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
